-- `Name` varchar(255) NOT NULL,`IndustryId` int(11),`FundsRaised` float(11,4) NOT NULL,`StageId` int(11) ,`LocationId` int(11) 

INSERT INTO COMPANY(Name, IndustryId, LocationId)
VALUES 
    ('99','Transportation','Sao Paulo'),
    ('Included Health','Healthcare','SF Bay Area'),
    ('100 Thieves','Consumer','Los Angeles'),
    ('10X Genomics','Healthcare','SF Bay Area'),
    ('1stdibs','Retail','New York City'),
    ('2TM','Crypto','Sao Paulo'),
    ('2U','Education','Washington D.C.'),
    ('54gene','Healthcare','Washington D.C.'),
    ('5B Solar','Energy','Sydney'),
    ('6sense','Sales','SF Bay Area'),
    ('98point6','Healthcare','Seattle'),
    ('Abra','Crypto','SF Bay Area'),
    ('Absci','Healthcare','Vancouver'),
    ('Acast','Media','Stockholm'),
    ('Acko','Finance','Mumbai'),
    ('Acorns','Finance','Portland'),
    ('Actifio','Data','Boston'),
    ('ActiveCampaign','Marketing','Chicago'),
    ('Ada','Support','Toronto'),
    ('Ada Health','Healthcare','Berlin'),
    ('Ada Support','Support','Toronto'),
    ('Adaptive Biotechnologies','Healthcare','Seattle'),
    ('Adara','Travel','SF Bay Area'),
    ('Addi','Finance','Bogota'),
    ('AdRoll','Marketing','Salt Lake City'),
    ('Advata','Healthcare','Seattle'),
    ('Adwerx','Marketing','Durham'),
    ('Affirm','Finance','SF Bay Area'),
    ('Agoda','Travel','Singapore'),
    ('Ahead','Healthcare','SF Bay Area'),
    ('Air','Marketing','New York City'),
    ('Airbnb','Travel','SF Bay Area'),
    ('Airlift','Logistics','Lahore'),
    ('Airtame','Consumer','Copenhagen'),
    ('Airtasker','Consumer','Sydney'),
    ('Airtime','Consumer','New York City'),
    ('Airy Rooms','Travel','Jakarta'),
    ('Akerna','Logistics','Denver'),
    ('Akulaku','Finance','Jakarta'),
    ('AlayaCare','Healthcare','Montreal'),
    ('Albert','Finance','Los Angeles'),
    ('Alegion','Data','Austin'),
    ('Alice','Healthcare','Sao Paulo'),
    ('AliExpress Russia','Retail','Moscow'),
    ('Allbirds','Retail','SF Bay Area'),
    ('AllyO','HR','SF Bay Area'),
    ('Alto Pharmacy','Healthcare','SF Bay Area'),
    ('Amber Group','Crypto','Hong Kong'),
    ('Amobee','Marketing','SF Bay Area'),
    ('Amount','Finance','Chicago'),
    ('Amperity','Marketing','Seattle'),
    ('Amplero','Marketing','Seattle'),
    ('Anagram','Healthcare','Los Angeles'),
    ('Andela','Recruiting','New York City'),
    ('AngelList','Recruiting','SF Bay Area'),
    ('Anodot','Data','Tel Aviv'),
    ('Antidote Health','Healthcare','Tel Aviv'),
    ('Anyvision','Security','Tel Aviv'),
    ('Anywell','Real Estate','Tel Aviv'),
    ('Apartment List','Real Estate','SF Bay Area'),
    ('Apeel Sciences','Food','Santa Barbara'),
    ('App Annie','Data','SF Bay Area'),
    ('AppGate','Security','Miami'),
    ('AppLovin','Marketing','SF Bay Area'),
    ('Aqgromalin','Food','Chennai'),
    ('Aqua Security','Security','Tel Aviv'),
    ('Arc','HR','SF Bay Area'),
    ('Arete','Security','Miami'),
    ('Argo AI','Transportation','Pittsburgh'),
    ('Argo AI','Transportation','Munich'),
    ('Argyle','Finance','New York City'),
    ('Arrival','Transportation','London'),
    ('Arrive Logistics','Logistics','Austin'),
    ('Article','Retail','Vancouver'),
    ('Artnight','Retail','Berlin'),
    ('AskNicely','Support','Portland'),
    ('Aspire','Marketing','SF Bay Area'),
    ('Atlanta Tech Village','Real Estate','Atlanta'),
    ('Atlas Obscura ','Media','New York City'),
    ('AtoB','Finance','SF Bay Area'),
    ('Atsu','Infrastructure','Seattle'),
    ('Aura','Security','Boston'),
    ('Aura Financial','Finance','SF Bay Area'),
    ('Automatic','Transportation','SF Bay Area'),
    ('Automox','Infrastructure','Boulder'),
    ('Avantage Entertainment','Media','Minneapolis'),
    ('AvantStay','Travel','Los Angeles'),
    ('Avo','Food','Tel Aviv'),
    ('Away','Retail','New York City'),
    ('Awok','Retail','Dubai'),
    ('Aya','Finance','Toronto'),
    ('B8ta','Retail','SF Bay Area'),
    ('Babylon','Healthcare','London'),
    ('Balto','Sales','St. Louis'),
    ('Bamboo Health','Healthcare','Louisville'),
    ('Banxa','Crypto','Melbourne'),
    ('Baton','Transportation','SF Bay Area'),
    ('Bcredi','Finance','Curitiba'),
    ('Beat','Transportation','Athens'),
    ('BeeTech','Finance','Sao Paulo'),
    ('Bench','Finance','Vancouver'),
    ('Benitago Group','Retail','New York City'),
    ('Berkeley Lights','Healthcare','SF Bay Area'),
    ('Berlin Brands Group','Retail','Berlin'),
    ('Bestow','Finance','Dallas'),
    ('Better.com','Real Estate','New York City'),
    ('BetterCloud','Security','New York City'),
    ('Betterfly','Healthcare','Santiago'),
    ('Bevi','Food','Boston'),
    ('Beyond Meat','Food','Los Angeles'),
    ('BeyondMinds','Data','Tel Aviv'),
    ('Big Fish Games','Media','Seattle'),
    ('BigBear.ai','Data','Baltimore'),
    ('Bikayi','Retail','Bengaluru'),
    ('Bird','Transportation','Los Angeles'),
    ('Bitfarms','Crypto','Quebec'),
    ('BitGo','Crypto','SF Bay Area'),
    ('BitMEX','Crypto','Non/U.S.'),
    ('BitOasis','Crypto','Dubai'),
    ('Bitpanda','Crypto','Vienna'),
    ('Bitrise','Infrastructure','Budapest'),
    ('Bitso','Crypto','Mexico City'),
    ('BitTitan','Data','Seattle'),
    ('Bizongo','Logistics','Mumbai'),
    ('Bizpay','Finance','Sydney'),
    ('Bizzabo','Marketing','New York City'),
    ('BlackBuck','Logistics','Bengaluru'),
    ('Bleacher Report','Media','London'),
    ('Blend','Finance','SF Bay Area'),
    ('Blockchain.com','Crypto','London'),
    ('BlockFi','Crypto','New York City'),
    ('Blueground','Real Estate','New York City'),
    ('Blume Global','Logistics','SF Bay Area'),
    ('Bluprint','Education','Denver'),
    ('Bolt','Finance','SF Bay Area'),
    ('Bond','Finance','SF Bay Area'),
    ('Bonsai','Retail','Toronto'),
    ('BookClub','Education','Salt Lake City'),
    ('Booking.com','Travel','Grand Rapids'),
    ('Booking.com','Travel','Amsterdam'),
    ('BookMyShow','Consumer','Mumbai'),
    ('Booksy','Consumer','SF Bay Area'),
    ('Booktopia','Retail','Sydney'),
    ('Boosted Commerce','Retail','Los Angeles'),
    ('Boozt','Retail','Malmo'),
    ('Borrowell','Finance','Toronto'),
    ('Bossa Nova','Retail','SF Bay Area'),
    ('Bounce','Transportation','Bengaluru'),
    ('BounceX','Marketing','New York City'),
    ('Brainly','Education','Krakow'),
    ('Branch','Retail','New York City'),
    ('Branch Metrics','Marketing','SF Bay Area'),
    ('Brave Care','Healthcare','Portland'),
    ('Breathe','Healthcare','New Delhi'),
    ('Breather','Real Estate','Montreal'),
    ('Brex','Finance','SF Bay Area'),
    ('Bridge Connector','Healthcare','Nashville'),
    ('Bright Machines','Data','SF Bay Area'),
    ('Bright Money','Finance','Bengaluru'),
    ('Brighte','Energy','Sydney'),
    ('Brightline','Healthcare','SF Bay Area'),
    ('Bringg','Logistics','Tel Aviv'),
    ('Bryter','Product','Berlin'),
    ('Buenbit','Crypto','Buenos Aires'),
    ('Builder','Product','Los Angeles'),
    ('Built In','Recruiting','Chicago'),
    ('Bullhorn','Sales','Boston'),
    ('Bullish','Crypto','Hong Kong'),
    ('Bungalow','Real Estate','SF Bay Area'),
    ('BusBud','Transportation','Montreal'),
    ('Bustle Digital Group','Media','New York City'),
    ('Butler Hospitality','Food','New York City'),
    ('Butterfly Network','Healthcare','New Haven'),
    ('Button','Marketing','New York City'),
    ('Buy.com / Rakuten','Retail','SF Bay Area'),
    ('Buzzer','Media','New York City'),
    ('BVAccel','Marketing','San Diego'),
    ('Bybit','Crypto','Singapore'),
    ('Byju''s','Education','Bengaluru'),
    ('Bytedance','Consumer','Shanghai'),
    ('Bytedance','Consumer','Mumbai'),
    ('Byton','Transportation','SF Bay Area'),
    ('C6 Bank','Finance','Sao Paulo'),
    ('Cabin','Travel','SF Bay Area'),
    ('Cadre','Real Estate','New York City'),
    ('Calibrate','Healthcare','New York City'),
    ('Caliva','Retail','SF Bay Area'),
    ('Callisto Media','Media','SF Bay Area'),
    ('Calm','Healthcare','SF Bay Area'),
    ('Cameo','Consumer','Chicago'),
    ('Candidate Labs','HR','SF Bay Area'),
    ('Canoo','Transportation','Los Angeles'),
    ('Capillary','Retail','Bengaluru'),
    ('Capiter','Finance','Cairo'),
    ('Capsule','Healthcare','New York City'),
    ('Carbon Health','Healthcare','SF Bay Area'),
    ('CarDekho','Transportation','Gurugram'),
    ('Care.com','Consumer','Boston'),
    ('Careem','Transportation','Dubai'),
    ('Career Karma','Education','SF Bay Area'),
    ('CarGurus','Transportation','Boston'),
    ('Cars24','Transportation','Gurugram'),
    ('Carsome','Transportation','Kuala Lumpur'),
    ('Carta','Finance','SF Bay Area'),
    ('Carvana','Transportation','Phoenix'),
    ('Casper','Retail','New York City'),
    ('Castlight Health','Healthcare','SF Bay Area'),
    ('Catalyst','Support','New York City'),
    ('Cazoo','Transportation','London'),
    ('Cedar','Healthcare','New York City'),
    ('Celsius','Crypto','New York City'),
    ('Cerebral','Healthcare','SF Bay Area'),
    ('Chargebee','Finance','SF Bay Area'),
    ('Checkmarx','Security','Tel Aviv'),
    ('Checkout.com','Finance','London'),
    ('Checkr','HR','SF Bay Area'),
    ('Cheddar','Media','New York City'),
    ('Cheetah','Food','SF Bay Area'),
    ('Chef','Infrastructure','Seattle'),
    ('Chessable','Consumer','London'),
    ('Chime','Finance','SF Bay Area'),
    ('ChowNow','Food','Los Angeles'),
    ('CipherTrace','Crypto','SF Bay Area'),
    ('Circ','Transportation','Berlin'),
    ('CircleUp','Finance','SF Bay Area'),
    ('Circulo Health','Healthcare','Columbus'),
    ('CityMall','Retail','Gurugram'),
    ('Claravine','Marketing','Salt Lake City'),
    ('Clari','Sales','SF Bay Area'),
    ('Clarify Health','Healthcare','SF Bay Area'),
    ('Classkick','Education','Chicago'),
    ('ClassPass','Fitness','New York City'),
    ('Clear','Finance','Bengaluru'),
    ('Clear Capital','Real Estate','SF Bay Area'),
    ('Clearbanc','Finance','Toronto'),
    ('Clearbit','Data','SF Bay Area'),
    ('Clearco','Finance','Toronto'),
    ('Clearco','Finance','Dublin'),
    ('Clever Real Estate','Real Estate','St. Louis'),
    ('CleverTap','Marketing','Mumbai'),
    ('Clinc','Support','Ann Arbor'),
    ('Cloudera','Infrastructure','SF Bay Area'),
    ('CloudKitchens','Real Estate','Los Angeles'),
    ('Clubhouse','Consumer','SF Bay Area'),
    ('Clumio','Data','SF Bay Area'),
    ('Clutch','Transportation','Toronto'),
    ('Clutter','Consumer','Los Angeles'),
    ('Clyde','Marketing','New York City'),
    ('Code42','Security','Minneapolis'),
    ('Code42','Data','Minneapolis');
INSERT INTO COMPANY VALUES
    ('CodeCombat','Education','SF Bay Area'),
    ('Coding Dojo','Education','Seattle'),
    ('Cogito','Support','Boston'),
    ('Cohesity','Data','SF Bay Area'),
    ('Coinbase','Crypto','SF Bay Area'),
    ('CoinFLEX','Crypto','Victoria'),
    ('Coinsquare','Crypto','Toronto'),
    ('Collibra','Data','Brussels'),
    ('Colossus','Energy','Boston'),
    ('CommentSold','Retail','Huntsville'),
    ('CommonBond','Finance','New York City'),
    ('Community','Marketing','Los Angeles'),
    ('Compass','Real Estate','New York City'),
    ('Compete','HR','Tel Aviv'),
    ('Conga','Data','Denver'),
    ('Connected','Product','Toronto'),
    ('ConsenSys','Crypto','New York City'),
    ('ContaAzul','Education','Joinville'),
    ('ContraFect','Healthcare','New York City'),
    ('Convene','Real Estate','New York City'),
    ('Convoy','Logistics','Seattle'),
    ('Copper','Marketing','SF Bay Area'),
    ('Core Scientific','Crypto','Austin'),
    ('Cosuno','Construction','Berlin'),
    ('Coterie Insurance','Finance','Cincinnati'),
    ('Coursera','Education','SF Bay Area'),
    ('Crayon','Marketing','Boston'),
    ('Credit Sesame','Finance','SF Bay Area'),
    ('Creditas','Finance','Sao Paulo'),
    ('Crehana','Education','Lima'),
    ('Crejo.Fun','Education','Bengaluru'),
    ('CrowdRiff','Marketing','Toronto'),
    ('CrowdStreet','Real Estate','Portland'),
    ('Cruise','Transportation','SF Bay Area'),
    ('Crypto.com','Crypto','Singapore'),
    ('CTO.ai','Infrastructure','Vancouver'),
    ('Cue','Healthcare','San Diego'),
    ('Culture Amp','HR','Melbourne'),
    ('Culture Trip','Media','London'),
    ('Curative','Healthcare','Los Angeles'),
    ('CureFit','Fitness','Bengaluru'),
    ('Curology','Healthcare','SF Bay Area'),
    ('Currency','Finance','Los Angeles'),
    ('Curve','Finance','London'),
    ('Cuyana','Retail','SF Bay Area'),
    ('Cvent','Marketing','Washington D.C.'),
    ('CyberCube','Finance','SF Bay Area'),
    ('Cybereason','Security','Boston'),
    ('D2iQ','Infrastructure','SF Bay Area'),
    ('Daily Harvest','Food','New York City'),
    ('DailyPay','Finance','New York City'),
    ('Daloopa','Data','New Delhi'),
    ('Daniel Wellington','Retail','Stockholm'),
    ('Dapper Labs','Crypto','Vancouver'),
    ('Dark','Product','SF Bay Area'),
    ('DataRobot','Data','Boston'),
    ('DataStax','Data','SF Bay Area'),
    ('Datera','Infrastructure','SF Bay Area'),
    ('Datto','Infrastructure','Norwalk'),
    ('DayTwo','Healthcare','SF Bay Area'),
    ('Dazn','Consumer','London'),
    ('Deep Instinct','Security','New York City'),
    ('Defined.ai','Data','Seattle'),
    ('Degreed','Education','SF Bay Area'),
    ('DeHaat','Food','Gurugram'),
    ('Deliv','Retail','SF Bay Area'),
    ('Deliveroo','Food','London'),
    ('Delivery Hero','Food','Berlin'),
    ('Demandbase','Sales','SF Bay Area'),
    ('Deputy','HR','Sydney'),
    ('Descartes Labs','Data','Santa Fe'),
    ('DialSource','Marketing','Sacramento'),
    ('Digital Currency Gruop','Crypto','Stamford'),
    ('DISCO','Legal','Austin'),
    ('Divergent 3D','Transportation','Los Angeles'),
    ('Divvy','Finance','Salt Lake City'),
    ('Divvy Homes','Real Estate','SF Bay Area'),
    ('divvyDOSE','Healthcare','Davenport'),
    ('DJI','Consumer','SF Bay Area'),
    ('DJI','Consumer','Shenzen'),
    ('Dock','Finance','Sao Paulo'),
    ('Docly','Healthcare','London'),
    ('DocuSign','Sales','SF Bay Area'),
    ('Doma','Finance','SF Bay Area'),
    ('Domestika','Education','SF Bay Area'),
    ('Domino Data Lab','Data','SF Bay Area'),
    ('Domio','Real Estate','New York City'),
    ('Domio','Travel','New York City'),
    ('Domo','Data','Salt Lake City'),
    ('Dooly','Sales','Vancouver'),
    ('Dotscience','Product','London'),
    ('Dover','Recruiting','SF Bay Area'),
    ('DreamBox Learning','Education','Seattle'),
    ('Drip','Marketing','Salt Lake City'),
    ('Drop','Marketing','Toronto'),
    ('DSCO','Retail','Salt Lake City'),
    ('Dukaan','Retail','Bengaluru'),
    ('Dynamic Signal','HR','SF Bay Area'),
    ('Earnin','Finance','SF Bay Area'),
    ('EasyPost','Logistics','SF Bay Area'),
    ('EasyPost','Logistics','Salt Lake City'),
    ('Eatsy','Food','Singapore'),
    ('Eaze','Consumer','SF Bay Area'),
    ('Ebanx','Finance','Curitiba'),
    ('Ecobee','Energy','Toronto'),
    ('Eden / Managed By Q','Real Estate','New York City'),
    ('Edmodo','Education','SF Bay Area'),
    ('eGym','Fitness','Munich'),
    ('Eight Sleep','Retail','New York City'),
    ('Ejento','Recruiting','SF Bay Area'),
    ('Element Analytics','Data','SF Bay Area'),
    ('Elementor','Media','Tel Aviv'),
    ('Elemy','Healthcare','SF Bay Area'),
    ('Elinvar','Finance','Berlin'),
    ('Elliptic','Crypto','London'),
    ('Embroker','Finance','SF Bay Area'),
    ('Emitwise','Energy','London'),
    ('Emotive','Marketing','Los Angeles'),
    ('Engine eCommerce','Retail','Fayetteville'),
    ('Enjoy','Retail','SF Bay Area'),
    ('Envato','Marketing','Melbourne'),
    ('Envoy','HR','SF Bay Area'),
    ('Equitybee','Finance','SF Bay Area'),
    ('EquityZen','Finance','New York City'),
    ('Eruditus','Education','Mumbai'),
    ('Esme Learning','Education','Boston'),
    ('Ethos Life','Finance','SF Bay Area'),
    ('eToro','Finance','Tel Aviv'),
    ('Eucalyptus','Healthcare','Sydney'),
    ('Eventbrite','Consumer','SF Bay Area'),
    ('Everlane','Retail','SF Bay Area'),
    ('Expert360','Recruiting','Sydney'),
    ('ExtraHop','Security','Seattle'),
    ('ezCater','Food','Boston'),
    ('FabHotels','Travel','New Delhi'),
    ('Fabric','Logistics','New York City'),
    ('Facily','Retail','Sao Paulo'),
    ('Faire','Retail','SF Bay Area'),
    ('Fandom','Media','SF Bay Area'),
    ('Fareportal','Travel','Gurugram'),
    ('FarEye','Logistics','New Delhi'),
    ('Fast','Finance','SF Bay Area'),
    ('Favo','Food','Sao Paulo'),
    ('Faze Medicines','Healthcare','Boston'),
    ('Feather','Retail','New York City'),
    ('Fifth Season','Food','Pittsburgh'),
    ('Finite State','Security','Columbus'),
    ('Finleap Connect','Finance','Hamburg'),
    ('Firebolt','Data','Tel Aviv'),
    ('First AML','Finance','Auckland'),
    ('FiscalNote','Media','Washington D.C.'),
    ('Fivetran','Data','SF Bay Area'),
    ('Flatiron School','Education','New York City'),
    ('Flipboard','Media','SF Bay Area'),
    ('Flockjay','Education','SF Bay Area'),
    ('FloQast','Finance','Los Angeles'),
    ('Flowhub','Retail','Denver'),
    ('Flowr','Retail','Toronto'),
    ('Flux Systems','Finance','London'),
    ('Flyhomes','Real Estate','Seattle'),
    ('Flymya','Travel','Yangon'),
    ('Flynote','Travel','Bengaluru'),
    ('Flytedesk','Marketing','Boulder'),
    ('Flywheel Sports','Fitness','New York City'),
    ('Flywire','Finance','Boston'),
    ('Food52','Food','New York City'),
    ('Foodpanda','Food','Singapore'),
    ('Foodpanda','Food','Bucharest'),
    ('Foodsby','Food','Minneapolis'),
    ('Forma.ai','Sales','Toronto'),
    ('Forward','Healthcare','SF Bay Area'),
    ('FourKites','Logistics','Chicago'),
    ('Foxtrot','Food','Chicago'),
    ('Fraazo','Food','Mumbai'),
    ('Freetrade','Finance','London'),
    ('Freshbooks','Finance','Toronto'),
    ('FreshDirect','Food','Philadelphia'),
    ('Freshly','Food','New York City'),
    ('Front','Support','SF Bay Area'),
    ('Frontdesk','Travel','Milwaukee'),
    ('FrontRow','Education','Bengaluru'),
    ('Frubana','Food','Bogota'),
    ('FuboTV','Media','New York City'),
    ('FullStory','Marketing','Atlanta'),
    ('Fundbox','Finance','SF Bay Area'),
    ('Funding Circle','Finance','SF Bay Area'),
    ('Funding Societies','Finance','Singapore'),
    ('Fungible','Crypto','SF Bay Area'),
    ('Furlenco','Retail','Bengaluru'),
    ('G/O Media Group','Media','New York City'),
    ('G2','Marketing','Chicago'),
    ('Gather','Consumer','SF Bay Area'),
    ('Gatherly','Marketing','Atlanta'),
    ('Gavelytics','Legal','Los Angeles'),
    ('Geekwire','Media','Seattle'),
    ('Gem','Recruiting','SF Bay Area'),
    ('Gemini','Crypto','New York City'),
    ('Genesis','Crypto','New York City'),
    ('Genius','Consumer','New York City'),
    ('Genome Medical','Healthcare','SF Bay Area'),
    ('Getaround','Transportation','SF Bay Area'),
    ('Getir','Food','Istanbul'),
    ('GetNinjas','Consumer','Sao Paulo'),
    ('Getta','Transportation','Tel Aviv'),
    ('GetYourGuide','Travel','Berlin'),
    ('Give Legacy','Healthcare','Boston'),
    ('Glassdoor','Recruiting','SF Bay Area'),
    ('Glitch','Product','New York City'),
    ('Glossier','Retail','New York City'),
    ('Glossier','Consumer','New York City'),
    ('GOAT Group','Retail','Los Angeles'),
    ('GoBear','Finance','Singapore'),
    ('GoCardless','Finance','London'),
    ('GoDaddy','Marketing','Austin'),
    ('GoFundMe','Finance','SF Bay Area'),
    ('GoHealth','Healthcare','Chicago'),
    ('Gojek','Transportation','Jakarta'),
    ('GoNuts','Media','Mumbai'),
    ('Goodfood','Food','Calgary'),
    ('GoodRx','Healthcare','Los Angeles'),
    ('GoPro','Consumer','SF Bay Area'),
    ('Gopuff','Food','Philadelphia'),
    ('Gorillas','Food','Berlin'),
    ('GoSpotCheck','Retail','Denver'),
    ('GoStudent','Education','Vienna'),
    ('GoTo Group','Transportation','Jakarta'),
    ('Grab','Transportation','Singapore'),
    ('Grailed','Retail','New York City'),
    ('GrayMeta','Data','Los Angeles'),
    ('Greenhouse Software','Recruiting','New York City'),
    ('Group Nine Media','Media','New York City'),
    ('Groupon','Retail','Chicago'),
    ('Grove Collaborative','Retail','SF Bay Area'),
    ('GSR','Crypto','Hong Kong'),
    ('Guidewire','Finance','SF Bay Area'),
    ('GumGum','Marketing','Los Angeles'),
    ('Gympass','Fitness','Sao Paulo'),
    ('Halcyon Health','Healthcare','New York City'),
    ('Handshake','Recruiting','SF Bay Area'),
    ('Hash','Finance','Sao Paulo'),
    ('Haus','Food','SF Bay Area'),
    ('Havenly','Consumer','Denver'),
    ('Healthcare.com','Healthcare','Miami'),
    ('HealthMatch','Healthcare','Sydney'),
    ('Hedvig','Finance','Stockholm'),
    ('HelloFresh','Food','SF Bay Area'),
    ('Help Scout','Support','Boston'),
    ('Help.com','Support','Austin'),
    ('Her Campus Media','Media','Boston'),
    ('Heroes','Retail','London');
INSERT INTO COMPANY VALUES
    ('Hibob','HR','Tel Aviv'),
    ('Highsnobiety','Media','Berlin'),
    ('Hipcamp','Travel','SF Bay Area'),
    ('Hippo Insurance','Finance','SF Bay Area'),
    ('Hired','Recruiting','SF Bay Area'),
    ('Hireology','Recruiting','Chicago'),
    ('Hodlnaut','Crypto','Singapore'),
    ('Hologram','Infrastructure','Chicago'),
    ('HomeLight','Real Estate','SF Bay Area'),
    ('Homeward','Real Estate','Austin'),
    ('Homie','Real Estate','Salt Lake City'),
    ('HOOQ','Consumer','Singapore'),
    ('Hootsuite','Marketing','Vancouver'),
    ('Hopper','Travel','Boston'),
    ('HopSkipDrive','Transportation','Los Angeles'),
    ('Horizn Studios','Travel','Berlin'),
    ('Hotmart','Marketing','Belo Horizonte'),
    ('Houzz','Consumer','SF Bay Area'),
    ('Hubba','Retail','Toronto'),
    ('HubHaus','Real Estate','SF Bay Area'),
    ('Hubilo','Marketing','SF Bay Area'),
    ('HuffPo','Media','New York City'),
    ('HumanForest','Transportation','London'),
    ('Humble','Media','SF Bay Area'),
    ('Humu','HR','SF Bay Area'),
    ('Hunty','HR','Bogota'),
    ('Huobi','Crypto','Beijing'),
    ('Hydrow','Fitness','Boston'),
    ('Hyperscience','Data','New York City'),
    ('Ibotta','Retail','Denver'),
    ('ID.me','Security','Washington D.C.'),
    ('Ideoclick','Retail','Seattle'),
    ('Iflix','Consumer','Kuala Lumpur'),
    ('Igenous','Data','Seattle'),
    ('Ignite','Crypto','SF Bay Area'),
    ('Ike','Transportation','SF Bay Area'),
    ('Immersive Labs','Security','Bristol'),
    ('Immutable','Crypto','Sydney'),
    ('Impact.com','Marketing','Los Angeles'),
    ('Impala','Travel','London'),
    ('Imperfect Foods','Food','SF Bay Area'),
    ('Impossible Foods','Food','SF Bay Area'),
    ('Incredible Health','Healthcare','SF Bay Area'),
    ('InDebted','Finance','Sydney'),
    ('Industrious','Real Estate','New York City'),
    ('Influitive','Marketing','Toronto'),
    ('InfoSum','Security','London'),
    ('Innovaccer','Healthcare','SF Bay Area'),
    ('Inspirato','Travel','Denver'),
    ('Instacart','Food','SF Bay Area'),
    ('Instamojo','Finance','Bengaluru'),
    ('Instructure','Education','Salt Lake City'),
    ('Intapp','Legal','SF Bay Area'),
    ('Integral Ad Science','Marketing','New York City'),
    ('Integrate.ai','Support','Toronto'),
    ('Intercom','Support','SF Bay Area'),
    ('Intersect','Product','Toronto'),
    ('Introhive','Sales','Ferdericton'),
    ('Intuit','Finance','SF Bay Area'),
    ('InVision','Product','New York City'),
    ('Invitae','Healthcare','SF Bay Area'),
    ('Involves','Retail','FlorianÃ³polis'),
    ('iPrice Group','Retail','Kuala Lumpur'),
    ('Iris Nova','Food','New York City'),
    ('IRL','Consumer','SF Bay Area'),
    ('iRobot','Consumer','Boston'),
    ('Iron Ox','Food','SF Bay Area'),
    ('IronNet','Security','Washington D.C.'),
    ('Jam City','Consumer','Los Angeles'),
    ('Jama','Product','Portland'),
    ('Jellysmack','Media','New York City'),
    ('JetClosing','Real Estate','Seattle'),
    ('Jetty','Finance','New York City'),
    ('Jiobit','Consumer','Chicago'),
    ('Jobcase','Recruiting','Boston'),
    ('JOKR','Food','New York City'),
    ('Jump','Transportation','New York City'),
    ('Juniper Square','Real Estate','SF Bay Area'),
    ('Just Eat Takeaway','Food','Amsterdam'),
    ('Juul','Consumer','SF Bay Area'),
    ('Kabam','Consumer','SF Bay Area'),
    ('Kaltura','Media','New York City'),
    ('Kaodim','Consumer','Selangor'),
    ('Kapten / Free Now','Transportation','Paris'),
    ('Katerra','Construction','SF Bay Area'),
    ('Kavak','Transportation','Sao Paulo'),
    ('Kayak / OpenTable','Travel','Stamford'),
    ('Kazoo','HR','Austin'),
    ('Keepe','Real Estate','Seattle'),
    ('KeepTruckin','Logistics','SF Bay Area'),
    ('Kenoby','Recruiting','Sao Paulo'),
    ('Khoros','Sales','Austin'),
    ('Kiavi','Real Estate','SF Bay Area'),
    ('Kickstarter','Finance','New York City'),
    ('Kitopi','Food','New York City'),
    ('KiwiCo','Retail','SF Bay Area'),
    ('Klarna','Finance','Stockholm'),
    ('Klook','Travel','Hong Kong'),
    ('Knock','Real Estate','New York City'),
    ('Knotel','Real Estate','New York City'),
    ('Kodiak Robotics','Transportation','SF Bay Area'),
    ('Kogan','Retail','Melbourne'),
    ('Komodo Health','Healthcare','SF Bay Area'),
    ('Konfio','Finance','Mexico City'),
    ('Kongregate','Media','SF Bay Area'),
    ('Kontist','Finance','Berlin'),
    ('Koo','Consumer','Bengaluru'),
    ('Kry','Healthcare','Stockholm'),
    ('Kuda','Finance','Lagos'),
    ('Kueski','Finance','Guadalajara'),
    ('Kune','Food','Nairobi'),
    ('kununu','Recruiting','Boston'),
    ('Labelbox','Data','SF Bay Area'),
    ('Labster','Education','Copenhagen'),
    ('Lacework','Security','SF Bay Area'),
    ('Ladder Life','Finance','SF Bay Area'),
    ('Lambda School','Education','SF Bay Area'),
    ('Landing','Real Estate','Birmingham'),
    ('Lastline','Security','SF Bay Area'),
    ('Latch','Security','New York City'),
    ('Lattice','HR','SF Bay Area'),
    ('Lawgeex','Legal','Tel Aviv'),
    ('Laybuy','Finance','Auckland'),
    ('Le Tote','Retail','SF Bay Area'),
    ('LEAD','Education','Mumbai'),
    ('Leafly','Retail','Seattle'),
    ('League','Healthcare','Toronto'),
    ('Legible','Media','Vancouver'),
    ('Lemonade','Finance','New York City'),
    ('Lending Club','Finance','SF Bay Area'),
    ('Lendingkart','Finance','Ahmedabad'),
    ('LetsGetChecked','Healthcare','New York City'),
    ('Levelset','Construction','New Orleans'),
    ('Lever','Recruiting','SF Bay Area'),
    ('Lido','Education','Mumbai'),
    ('Lido Learning','Education','Mumbai'),
    ('Lighter Capital','Finance','Seattle'),
    ('Lighthouse Labs','Education','Toronto'),
    ('Lightricks','Consumer','Jerusalem'),
    ('Lime','Transportation','SF Bay Area'),
    ('Limelight','Recruiting','New York City'),
    ('LinkedIn','Recruiting','SF Bay Area'),
    ('Linkfire','Marketing','Copenhagen'),
    ('Linktree','Consumer','Melbourne'),
    ('Liongard','Infrastructure','Houston'),
    ('Liv Up','Food','Sao Paulo'),
    ('LivePerson','Support','New York City'),
    ('LiveRamp','Marketing','SF Bay Area'),
    ('Livspace','Retail','Bengaluru'),
    ('Loft','Real Estate','Sao Paulo'),
    ('Loftium','Real Estate','Seattle'),
    ('Loftsmart','Real Estate','New York City'),
    ('Loggi','Logistics','Sao Paulo'),
    ('Loja Integrada','Retail','Sao Paulo'),
    ('Lola','Travel','Boston'),
    ('Loom','Product','SF Bay Area'),
    ('Loop','Finance','Washington D.C.'),
    ('Loopio','Sales','Toronto'),
    ('LoopMe','Marketing','London'),
    ('LumenAd','Marketing','Missoula'),
    ('Lumina Networks','Infrastructure','SF Bay Area'),
    ('Lummo','Marketing','Jakarta'),
    ('Lunchbox','Food','New York City'),
    ('Lusha','Marketing','New York City'),
    ('Lyft','Transportation','SF Bay Area'),
    ('Lyric','Real Estate','SF Bay Area'),
    ('Lytics','Marketing','Portland'),
    ('M1','Finance','Chicago'),
    ('Made.com','Retail','London'),
    ('Madefire','Media','SF Bay Area'),
    ('MadeiraMadeira','Retail','Curitiba'),
    ('Magic Leap','Consumer','Miami'),
    ('Magicbricks','Real Estate','Noida'),
    ('Mainstreet','Finance','SF Bay Area'),
    ('Make School','Education','SF Bay Area'),
    ('MakeMyTrip','Travel','New Delhi'),
    ('MakeMyTrip','Travel','Gurugram'),
    ('MakerBot','Consumer','New York City'),
    ('Malwarebytes','Security','SF Bay Area'),
    ('Mapbox','Data','Washington D.C.'),
    ('Mapify','Travel','Berlin'),
    ('Marketforce','Retail','Nairobi'),
    ('Masse','Retail','New York City'),
    ('MasterClass','Education','SF Bay Area'),
    ('Matterport','Data','SF Bay Area'),
    ('Maven','Media','Seattle'),
    ('MaxMilhas','Travel','Belo Horizonte'),
    ('McMakler','Real Estate','Berlin'),
    ('MediaMath','Marketing','New York City'),
    ('Medium','Media','SF Bay Area'),
    ('Medly','Healthcare','New York City'),
    ('Meesho','Retail','Bengaluru'),
    ('Mejuri','Retail','Toronto'),
    ('Melio','Finance','New York City'),
    ('Memmo','Consumer','Stockholm'),
    ('Meow Wolf','Media','Santa Fe'),
    ('Mercos','Sales','Joinville'),
    ('Meta','Consumer','SF Bay Area'),
    ('Metigy','Marketing','Sydney'),
    ('Metromile','Finance','SF Bay Area'),
    ('Mews','Travel','Prague'),
    ('MFine','Healthcare','Bengaluru'),
    ('Migo','Finance','SF Bay Area'),
    ('MindBody','Fitness','San Luis Obispo'),
    ('Mindgeek','Media','Luxembourg'),
    ('Minted','Retail','SF Bay Area'),
    ('MissFresh','Food','Beijing'),
    ('Mixpanel','Data','SF Bay Area'),
    ('Mobile Premier League','Consumer','Bengaluru'),
    ('Mode Analytics','Data','SF Bay Area'),
    ('Modsy','Retail','SF Bay Area'),
    ('Mogo','Finance','Vancouver'),
    ('Momentive','Marketing','SF Bay Area'),
    ('Monese','Finance','Lisbon'),
    ('Monzo','Finance','London'),
    ('Monzo','Finance','Las Vegas'),
    ('Moovel','Transportation','Portland'),
    ('Moss','Finance','Berlin'),
    ('Motif Foodworks','Food','Boston'),
    ('Motif Investing','Finance','SF Bay Area'),
    ('Movidesk','Support','Blumenau'),
    ('Mozilla','Consumer','SF Bay Area'),
    ('Mr. Yum','Food','Melbourne'),
    ('Mural','Product','SF Bay Area'),
    ('Mux','Infrastructure','SF Bay Area'),
    ('MX','Finance','Lehi'),
    ('Mythical Games','Crypto','Los Angeles'),
    ('N26','Finance','New York City'),
    ('Namely','HR','New York City'),
    ('Nate','Retail','New York City'),
    ('Nativo','Marketing','Los Angeles'),
    ('Nav','Finance','Salt Lake City'),
    ('Navi','Finance','Bengaluru'),
    ('Nearmap','Construction','Sydney'),
    ('Neon','Finance','Sao Paulo'),
    ('Netflix','Media','SF Bay Area'),
    ('New Relic','Infrastructure','SF Bay Area'),
    ('New Relic','Infrastructure','Portland'),
    ('Newfront Insurance','Finance','SF Bay Area'),
    ('Next Insurance','Finance','SF Bay Area'),
    ('Nextbite','Food','Denver'),
    ('NextRoll','Marketing','SF Bay Area'),
    ('Niantic','Consumer','SF Bay Area'),
    ('Ninjacart','Food','Bengaluru'),
    ('Nomad','Finance','Sao Paulo'),
    ('Noom','Healthcare','New York City'),
    ('Notarize','Legal','Boston'),
    ('Nova Benefits','Healthcare','Bengaluru'),
    ('NS8','Data','Las Vegas'),
    ('NSO','Security','Tel Aviv');
INSERT INTO COMPANY VALUES
    ('Numbrs','Finance','Zurich'),
    ('NuoDB','Data','Boston'),
    ('Nuri','Crypto','Berlin'),
    ('Nuri','Finance','Berlin'),
    ('Nuro','Transportation','SF Bay Area'),
    ('Nutanix','Infrastructure','SF Bay Area'),
    ('NYDIG','Crypto','New York City'),
    ('Nylas','Product','SF Bay Area'),
    ('Nyriad','Infrastructure','Austin'),
    ('Ocavu','Crypto','Lehi'),
    ('Oda','Food','Oslo'),
    ('Oh My Green','Food','SF Bay Area'),
    ('OKCredit','Finance','New Delhi'),
    ('Ola','Transportation','Bengaluru'),
    ('Olist','Retail','Curitiba'),
    ('Olive','Healthcare','Columbus'),
    ('OLX India','Marketing','New Delhi'),
    ('Omie','Finance','Sao Paulo'),
    ('On Deck','Education','SF Bay Area'),
    ('OnDeck','Finance','New York City'),
    ('OneTrust','Security','Atlanta'),
    ('OneTrust','Legal','Atlanta'),
    ('OnlyFans','Media','London'),
    ('Opal','Marketing','Portland'),
    ('OPay','Finance','Lagos'),
    ('Opencare','Healthcare','Toronto'),
    ('Opendoor','Real Estate','SF Bay Area'),
    ('OpenSea','Crypto','New York City'),
    ('OpenWeb','Media','Tel Aviv'),
    ('OpenX','Marketing','Los Angeles'),
    ('Optimizely','Marketing','SF Bay Area'),
    ('OrCam','Healthcare','Jerusalem'),
    ('Orchard','Real Estate','New York City'),
    ('O''Reilly Media','Media','SF Bay Area'),
    ('Oriente','Finance','Hong Kong'),
    ('Oscar Health','Healthcare','New York City'),
    ('Otonomo','Transportation','Tel Aviv'),
    ('Ouster','Transportation','SF Bay Area'),
    ('OutboundEngine','Marketing','Austin'),
    ('Outbrain','Marketing','New York City'),
    ('Outdoorsy','Transportation','SF Bay Area'),
    ('Outreach','Sales','Seattle'),
    ('Outschool','Education','SF Bay Area'),
    ('Outside','Media','Boulder'),
    ('Overtime','Media','New York City'),
    ('Owlet','Healthcare','Lehi'),
    ('Oye Rickshaw','Transportation','New Delhi'),
    ('OYO','Travel','Gurugram'),
    ('OYO','Travel','Dallas'),
    ('OYO','Travel','London'),
    ('OYO','Travel','Sao Paulo'),
    ('Ozy Media','Media','SF Bay Area'),
    ('Pacaso','Real Estate','SF Bay Area'),
    ('Packable','Retail','New York City'),
    ('PACT Pharma','Healthcare','SF Bay Area'),
    ('Pagarbook','HR','Bengaluru'),
    ('PaisaBazaar','Finance','Gurugram'),
    ('Pana','Travel','Denver'),
    ('Panda Squad','Consumer','SF Bay Area'),
    ('Parallel Wireless','Infrastructure','Nashua'),
    ('Pared','Food','SF Bay Area'),
    ('Parsable','HR','SF Bay Area'),
    ('Passport','Transportation','Charlotte'),
    ('Pastel','Food','SF Bay Area'),
    ('PatientPop','Healthcare','Los Angeles'),
    ('Patreon','Media','SF Bay Area'),
    ('Pavilion Data','Infrastructure','SF Bay Area'),
    ('Payfactors','HR','Boston'),
    ('PayJoy','Finance','SF Bay Area'),
    ('PayPal','Finance','SF Bay Area'),
    ('PaySense','Finance','Mumbai'),
    ('Paytm','Finance','New Delhi'),
    ('Pear Therapeutics ','Healthcare','Boston'),
    ('Pebblepost','Marketing','New York City'),
    ('Peek','Travel','Salt Lake City'),
    ('Peerfit','HR','Tampa Bay'),
    ('Peerspace','Real Estate','SF Bay Area'),
    ('PeerStreet','Finance','Los Angeles'),
    ('Peloton','Fitness','New York City'),
    ('Pendo','Product','Raleigh'),
    ('People.ai','Sales','SF Bay Area'),
    ('People.ai','Marketing','SF Bay Area'),
    ('PeopleGrove','HR','SF Bay Area'),
    ('Perceptive Automata','Transportation','Boston'),
    ('Perion','Marketing','Tel Aviv'),
    ('Perkbox','HR','London'),
    ('PerkSpot','HR','Chicago'),
    ('Permutive','Marketing','London'),
    ('Perx Health','Healthcare','Sydney'),
    ('Petal','Finance','New York City'),
    ('PharmEasy','Healthcare','Mumbai'),
    ('PickYourTrail','Travel','Chennai'),
    ('PicoBrew','Food','Seattle'),
    ('Picsart','Consumer','Miami'),
    ('Pipedrive','Sales','Tallin'),
    ('Pipl','Security','Spokane'),
    ('Pitch','Marketing','Berlin'),
    ('Pivot3','Infrastructure','Austin'),
    ('Pix','Food','SF Bay Area'),
    ('Plato','HR','SF Bay Area'),
    ('Playdots','Consumer','New York City'),
    ('Playtika','Consumer','Tel Aviv'),
    ('Pleo','Finance','Copenhagen'),
    ('Pliops','Data','Tel Aviv'),
    ('Plum','Healthcare','Bengaluru'),
    ('Pocketmath','Marketing','Singapore'),
    ('Polarr','Consumer','SF Bay Area'),
    ('PolicyGenius','Finance','New York City'),
    ('Politico / Protocol','Media','Washington D.C.'),
    ('Pollen','Marketing','London'),
    ('Pollen','Travel','London'),
    ('Pomelo Fashion','Retail','Bangkok'),
    ('Popin','Fitness','New York City'),
    ('Postmates','Food','SF Bay Area'),
    ('Postscript','Marketing','SF Bay Area'),
    ('PowerReviews','Retail','Chicago'),
    ('Practically','Education','Hyderabad'),
    ('Preply','Education','Boston'),
    ('Privitar','Data','London'),
    ('Procore','Construction','Los Angeles'),
    ('Project44','Logistics','Chicago'),
    ('Propzy','Real Estate','Ho Chi Minh City'),
    ('Provi','Food','Chicago'),
    ('Pulse Secure','Security','SF Bay Area'),
    ('Puppet','Infrastructure','Portland'),
    ('Purse','Crypto','SF Bay Area'),
    ('Qin1','Education','Noida'),
    ('Quandoo','Food','Berlin'),
    ('Quantcast','Marketing','SF Bay Area'),
    ('Quanto','Finance','Sao Paulo'),
    ('Quartz','Media','New York City'),
    ('Quibi','Media','Los Angeles'),
    ('Quicko','Transportation','Sao Paulo'),
    ('QuintoAndar','Real Estate','Sao Paulo'),
    ('Qumulo','Data','Seattle'),
    ('Qwick','Recruiting','Phoenix'),
    ('Rad Power Bikes','Transportation','Seattle'),
    ('Rain','Finance','Manama'),
    ('RainFocus','Marketing','Salt Lake City'),
    ('Raken','Construction','San Diego'),
    ('Rangle','Product','Toronto'),
    ('Rasa','Data','Berlin'),
    ('Reali','Real Estate','SF Bay Area'),
    ('RealSelf','Healthcare','Seattle'),
    ('Realtor.com','Real Estate','SF Bay Area'),
    ('Recharge','Finance','Los Angeles'),
    ('RedDoorz','Travel','Singapore'),
    ('Redesign Health','Healthcare','New York City'),
    ('Redfin','Real Estate','Seattle'),
    ('Redox','Healthcare','Madison'),
    ('Reef','Transportation','Miami'),
    ('Reforge','Education','SF Bay Area'),
    ('Remedy','Healthcare','Austin'),
    ('Remesh','Support','New York City'),
    ('Remote','HR','SF Bay Area'),
    ('Remote Year','Travel','Chicago'),
    ('Renmoney','Finance','Lagos'),
    ('RenoRun','Construction','Montreal'),
    ('Rent the Runway','Retail','New York City'),
    ('Repertoire Immune Medicines','Healthcare','Boston'),
    ('Replicated','Infrastructure','Los Angeles'),
    ('Restaurant365','Food','Los Angeles'),
    ('Rev.com','Data','Austin'),
    ('Revolut','Finance','London'),
    ('Rhino','Real Estate','New York City'),
    ('Rhumbix','Construction','SF Bay Area'),
    ('Ribbon','Real Estate','New York City'),
    ('Ridecell','Transportation','SF Bay Area'),
    ('RigUp','Energy','Austin'),
    ('RingCentral','Support','SF Bay Area'),
    ('Ritual','Food','Toronto'),
    ('Rivian','Transportation','Detroit'),
    ('Ro','Healthcare','New York City'),
    ('Robinhood','Finance','SF Bay Area'),
    ('Rock Content','Marketing','Belo Horizonte'),
    ('Roofstock','Real Estate','SF Bay Area'),
    ('Root Insurance','Finance','Columbus'),
    ('Rover','Consumer','Seattle'),
    ('Rubica','Security','Seattle'),
    ('Rubicon Project','Marketing','Los Angeles'),
    ('Rubrik','Infrastructure','SF Bay Area'),
    ('Rupeek','Finance','Bengaluru'),
    ('SafeGraph','Data','SF Bay Area'),
    ('Sage Therapeutics','Healthcare','Boston'),
    ('Sales Boomerang','Sales','Baltimore'),
    ('Salesforce','Sales','SF Bay Area'),
    ('SalesLoft','Sales','Atlanta'),
    ('Salsify','Retail','Boston'),
    ('Sama','Data','SF Bay Area'),
    ('Sami','Healthcare','Sao Paulo'),
    ('Samsara','Logistics','SF Bay Area'),
    ('Sanar','Healthcare','Sao Paulo'),
    ('Sandbox VR','Consumer','SF Bay Area'),
    ('Sauce Labs','Infrastructure','SF Bay Area'),
    ('ScaleFactor','Finance','Austin'),
    ('ScaleFocus','Infrastructure','Sofia'),
    ('Scoop','Transportation','SF Bay Area'),
    ('Sea','Consumer','Singapore'),
    ('Sea','Retail','Bengaluru'),
    ('Secfi','Finance','SF Bay Area'),
    ('Section4','Education','New York City'),
    ('Seegrid','Logistics','Pittsburgh'),
    ('Segment','Data','SF Bay Area'),
    ('SellerX','Retail','Berlin'),
    ('Sema4','Healthcare','Stamford'),
    ('SEND','Food','Sydney'),
    ('SendCloud','Logistics','Eindhoven'),
    ('Sendle','Logistics','Sydney'),
    ('Sendoso','Marketing','SF Bay Area'),
    ('Sendy','Logistics','Nairobi'),
    ('Sensibill','Finance','Toronto'),
    ('Service','Travel','Los Angeles'),
    ('Sezzle','Finance','Minneapolis'),
    ('ShareChat','Marketing','Bengaluru'),
    ('Sharethrough','Marketing','SF Bay Area'),
    ('Shef','Food','SF Bay Area'),
    ('Shelf Engine','Food','Seattle'),
    ('Sherpa','Travel','Toronto'),
    ('Shift','Transportation','SF Bay Area'),
    ('ShipBob','Logistics','Chicago'),
    ('Shippo','Logistics','SF Bay Area'),
    ('Shipsi','Retail','Los Angeles'),
    ('Shogun','Retail','SF Bay Area'),
    ('Shop101','Retail','Mumbai'),
    ('Shopee','Food','Jakarta'),
    ('Shopee','Food','Singapore'),
    ('Shopify','Retail','Ottawa'),
    ('ShopX','Retail','Bengaluru'),
    ('Showpad','Marketing','Chicago'),
    ('Shuttl','Transportation','New Delhi'),
    ('Side','Real Estate','SF Bay Area'),
    ('Sidecar Health','Healthcare','Los Angeles'),
    ('Sift','Security','SF Bay Area'),
    ('Signicat','Security','Trondheim'),
    ('Simon Data','Marketing','New York City'),
    ('Simple','Finance','Portland'),
    ('Simple Feast','Food','Copenhagen'),
    ('Singular','Marketing','SF Bay Area'),
    ('Sisense','Data','New York City'),
    ('Siteimprove','Marketing','Minneapolis'),
    ('Skai','Marketing','Tel Aviv'),
    ('Skedulo','HR','SF Bay Area'),
    ('Skillshare','Education','New York City'),
    ('Skillz','Consumer','SF Bay Area'),
    ('SkipTheDishes','Food','Winnipeg'),
    ('Skyscanner','Travel','Edinburgh'),
    ('SkySlope','Real Estate','Sacramento'),
    ('Slice Labs','Finance','New York City'),
    ('Slync','Logistics','Dallas'),
    ('Smava','Finance','Berlin');
INSERT INTO COMPANY VALUES
    ('Snagajob','HR','Richmond'),
    ('Snap','Consumer','Los Angeles'),
    ('Snap Finance','Finance','Salt Lake City'),
    ('Snapdocs','Real Estate','SF Bay Area'),
    ('Snaptravel','Travel','Toronto'),
    ('Snyk','Security','Boston'),
    ('Socure','Finance','Reno'),
    ('SoFi','Finance','SF Bay Area'),
    ('Sojern','Marketing','SF Bay Area'),
    ('Solarisbank','Finance','Berlin'),
    ('Soluto','Support','Tel Aviv'),
    ('Sonder','Travel','SF Bay Area'),
    ('Sonos','Consumer','New York City'),
    ('Sorabel','Retail','Jakarta'),
    ('SoundCloud','Consumer','Berlin'),
    ('Sourcegraph','Product','SF Bay Area'),
    ('Spaces','Media','Los Angeles'),
    ('Spin','Transportation','SF Bay Area'),
    ('Splice','Media','New York City'),
    ('Splunk','Data','SF Bay Area'),
    ('SpotHero','Transportation','Chicago'),
    ('Spotify','Media','Stockholm'),
    ('Spreetail','Retail','Austin'),
    ('Spring','Retail','SF Bay Area'),
    ('Springlane','Food','DÃ¼sseldorf'),
    ('Sprinklr','Support','New York City'),
    ('Spyce','Food','Boston'),
    ('SQream','Data','New York City'),
    ('SquadVoice','Real Estate','Columbus'),
    ('Stack Overflow','Recruiting','New York City'),
    ('Starship','Transportation','SF Bay Area'),
    ('Starship Technologies','Transportation','Tallin'),
    ('Stash Financial','Finance','New York City'),
    ('Stashaway','Finance','Singapore'),
    ('Stay Alfred','Travel','Spokane'),
    ('Stedi','Product','Boulder'),
    ('Stint','HR','London'),
    ('Stitch Fix','Retail','SF Bay Area'),
    ('Stockwell AI','Retail','SF Bay Area'),
    ('StockX','Retail','Detroit'),
    ('Stone','Finance','Sao Paulo'),
    ('Stoqo','Food','Jakarta'),
    ('Stord','Logistics','Atlanta'),
    ('Storytel','Media','Stockholm'),
    ('Stream','Product','Boulder'),
    ('StreamElements','Media','Tel Aviv'),
    ('StreamSets','Data','SF Bay Area'),
    ('Stripe','Finance','SF Bay Area'),
    ('StubHub','Consumer','SF Bay Area'),
    ('Studio','Education','SF Bay Area'),
    ('StyleSeat','Consumer','SF Bay Area'),
    ('Subspace','Infrastructure','Los Angeles'),
    ('Substack','Media','SF Bay Area'),
    ('SummerBio','Healthcare','SF Bay Area'),
    ('SumUp','Finance','Sao Paulo'),
    ('SumUp','Finance','London'),
    ('Sundae','Real Estate','SF Bay Area'),
    ('Sunday','Finance','Atlanta'),
    ('SundaySky','Marketing','New York City'),
    ('Superhuman','Consumer','SF Bay Area'),
    ('SuperLearn','Education','Bengaluru'),
    ('Superloop','Infrastructure','Brisbane'),
    ('Superpedestrian','Transportation','Boston'),
    ('Swappie','Retail','Helsinki'),
    ('SweetEscape','Consumer','Jakarta'),
    ('Sweetgreen','Food','Los Angeles'),
    ('Swiggy','Food','Bengaluru'),
    ('Swing Education','Education','SF Bay Area'),
    ('SWVL','Transportation','Dubai'),
    ('Swyft','Logistics','Toronto'),
    ('Swyftx','Crypto','Brisbane'),
    ('SynapseFI','Finance','SF Bay Area'),
    ('Synapsica','Healthcare','New Delhi'),
    ('Synergysuite','Food','Salt Lake City'),
    ('Syte','Retail','Tel Aviv'),
    ('Taboola','Marketing','New York City'),
    ('Takl','Consumer','Nashville'),
    ('Talis Biomedical','Healthcare','SF Bay Area'),
    ('Talkdesk','Support','SF Bay Area'),
    ('Talkwalker','Marketing','Luxembourg'),
    ('Tally','Finance','SF Bay Area'),
    ('Tamara Mellon','Retail','Los Angeles'),
    ('Tanium','Security','Seattle'),
    ('Tapas Media','Media','SF Bay Area'),
    ('TaskUs','Support','Los Angeles'),
    ('TechAdvance','Finance','Lagos'),
    ('Teleport','Infrastructure','SF Bay Area'),
    ('Tempo','Fitness','SF Bay Area'),
    ('Tempus Ex','Data','SF Bay Area'),
    ('Terminus','Marketing','Atlanta'),
    ('Tesla','Transportation','Austin'),
    ('Textio','Recruiting','Seattle'),
    ('TextNow','Consumer','Waterloo'),
    ('The Appraisal Lane','Transportation','Montevideo'),
    ('The Athletic','Media','SF Bay Area'),
    ('The Grommet','Retail','Boston'),
    ('The Guild','Travel','Austin'),
    ('The Modist','Retail','Dubai'),
    ('The Mom Project','HR','Chicago'),
    ('The Muse','Recruiting','New York City'),
    ('The Org','HR','New Delhi'),
    ('The Predictive Index','HR','Boston'),
    ('The RealReal','Retail','SF Bay Area'),
    ('The Sill','Retail','New York City'),
    ('The Wing','Real Estate','New York City'),
    ('The Zebra','Finance','Austin'),
    ('TheSkimm','Media','New York City'),
    ('TheWrap','Media','Los Angeles'),
    ('Thimble','Finance','New York City'),
    ('Thinkific','Education','Vancouver'),
    ('ThirdLove','Retail','SF Bay Area'),
    ('ThirdLove','Retail','New York City'),
    ('Thirty Madison','Healthcare','New York City'),
    ('ThoughtSpot','Data','SF Bay Area'),
    ('Thrasio','Retail','Boston'),
    ('ThredUp','Retail','Chicago'),
    ('Thriver','Food','Toronto'),
    ('Thumbtack','Consumer','SF Bay Area'),
    ('Tidepool','Healthcare','SF Bay Area'),
    ('Tiendanube','Marketing','Buenos Aires'),
    ('Tier Mobility','Transportation','Berlin'),
    ('TIFIN','Crypto','Boulder'),
    ('TikTok','Consumer','Los Angeles'),
    ('Toast','Food','Boston'),
    ('Tomo','Finance','Stamford'),
    ('Tonal','Fitness','SF Bay Area'),
    ('Top Hat','Education','Toronto'),
    ('Toppr','Education','Mumbai'),
    ('Tor','Security','Boston'),
    ('TouchBistro','Food','Toronto'),
    ('Trade Republic','Finance','Berlin'),
    ('Transfix','Logistics','New York City'),
    ('Transmit Security','Security','Boston'),
    ('TravelBank','Travel','SF Bay Area'),
    ('Traveloka','Travel','Jakarta'),
    ('TravelTriangle','Travel','Gurugram'),
    ('Trax','Retail','Singapore'),
    ('Trax','Retail','Tel Aviv'),
    ('Tray.io','Data','SF Bay Area'),
    ('Treehouse','Education','Portland'),
    ('Trell','Retail','Bengaluru'),
    ('TripActions','Travel','SF Bay Area'),
    ('TripAdvisor','Travel','Boston'),
    ('Tripbam','Travel','Dallas'),
    ('Triplebyte','Recruiting','SF Bay Area'),
    ('TripleLift','Marketing','New York City'),
    ('Tripwire','Security','Portland'),
    ('Trivago','Travel','Dusseldorf'),
    ('Trove Recommerce','Retail','SF Bay Area'),
    ('Truck It In','Logistics','Karachi'),
    ('TrueCar','Transportation','Los Angeles'),
    ('TrueLayer','Finance','London'),
    ('Truepill','Healthcare','SF Bay Area'),
    ('Truiloo','Security','Vancouver'),
    ('Trustly','Finance','Stockholm'),
    ('Trybe','Education','Sao Paulo'),
    ('Tufin','Security','Boston'),
    ('Tuft & Needle','Retail','Phoenix'),
    ('Tulip Retail','Retail','Toronto'),
    ('Turnitin','Education','SF Bay Area'),
    ('Turntide','Energy','SF Bay Area'),
    ('Turo','Transportation','SF Bay Area'),
    ('TutorMundi','Education','Sao Paulo'),
    ('TwinStrand','Healthcare','Seattle'),
    ('Twitter','Consumer','SF Bay Area'),
    ('tZero','Finance','New York City'),
    ('Uber','Transportation','Vilnius'),
    ('Uber','Transportation','Amsterdam'),
    ('Uber','Transportation','Bengaluru'),
    ('Uber','Transportation','SF Bay Area'),
    ('Uberflip','Marketing','Toronto'),
    ('Udaan','Retail','Bengaluru'),
    ('Udacity','Education','SF Bay Area'),
    ('Udayy','Education','Gurugram'),
    ('UiPath','Data','New York City'),
    ('Una Brands','Retail','Singapore'),
    ('Unacademy','Education','Bengaluru'),
    ('Unbabel','Support','Lisbon'),
    ('Unbounce','Marketing','Vancouver'),
    ('Uncapped','Finance','London'),
    ('Unison','Finance','SF Bay Area'),
    ('Universal Standard','Retail','New York City'),
    ('Unstoppable Domains','Crypto','SF Bay Area'),
    ('UPshow','Marketing','Chicago'),
    ('Upstart','Finance','SF Bay Area'),
    ('Urban Sports Club','Fitness','Berlin'),
    ('Usermind','Marketing','Seattle'),
    ('uShip','Logistics','Austin'),
    ('Vacasa','Travel','Portland'),
    ('Validity','Data','Boston'),
    ('VanHack','HR','Vancouver'),
    ('Varo','Finance','SF Bay Area'),
    ('Varonis','Security','New York City'),
    ('Vedanta Biosciences','Healthcare','Boston'),
    ('Vedantu','Education','Bengaluru'),
    ('Vee','HR','Tel Aviv'),
    ('Veem','Finance','SF Bay Area'),
    ('Veev','Real Estate','SF Bay Area'),
    ('Velodyne Lidar','Transportation','SF Bay Area'),
    ('Vendasta','Marketing','Saskatoon'),
    ('Verbit','Data','New York City'),
    ('Veriff','Security','Tallin'),
    ('Vesalius Therapeutics','Healthcare','Boston'),
    ('Vesta','Sales','Atlanta'),
    ('Vezeeta','Healthcare','Dubai'),
    ('VideoAmp','Marketing','Los Angeles'),
    ('View','Energy','SF Bay Area'),
    ('Vimeo','Consumer','New York City'),
    ('Virgin Hyperloop','Transportation','Los Angeles'),
    ('Virta Health','Healthcare','SF Bay Area'),
    ('Virtudent','Healthcare','Boston'),
    ('Vise','Finance','New York City'),
    ('Voi','Transportation','Stockholm'),
    ('Volt Bank','Finance','Sydney'),
    ('Volta','Transportation','SF Bay Area'),
    ('Voly','Food','Sydney'),
    ('Vouch','Finance','SF Bay Area'),
    ('Vox Media','Media','Washington D.C.'),
    ('Voyage SMS','Marketing','Los Angeles'),
    ('Vroom','Transportation','New York City'),
    ('VSCO','Consumer','SF Bay Area'),
    ('VTEX','Retail','Sao Paulo'),
    ('Wahoo Fitness','Fitness','Atlanta'),
    ('WanderJaunt','Travel','SF Bay Area'),
    ('Warby Parker','Consumer','New York City'),
    ('Warren','Finance','Porto Alegre'),
    ('Wave','Finance','Dakar'),
    ('Wave Sports and Entertainment','Media','Los Angeles'),
    ('Wavely','HR','SF Bay Area'),
    ('Wayfair','Retail','Boston'),
    ('Waze','Transportation','SF Bay Area'),
    ('WazirX','Crypto','Mumbai'),
    ('Wealthsimple','Finance','Toronto'),
    ('WeDoctor','Healthcare','Non/U.S.'),
    ('Weee!','Food','SF Bay Area'),
    ('WeFit','Fitness','Hanoi'),
    ('Welkin Health','Healthcare','SF Bay Area'),
    ('Westwing','Retail','Munich'),
    ('WeWork','Real Estate','London'),
    ('WeWork','Real Estate','SF Bay Area'),
    ('WeWork','Real Estate','New York City'),
    ('WeWork','Real Estate','New Delhi'),
    ('WeWork ','Real Estate','Shenzen'),
    ('Wheel','Healthcare','Austin'),
    ('When I Work','HR','Minneapolis'),
    ('WhiteHat Jr','Education','Mumbai'),
    ('WHOOP','Fitness','Boston'),
    ('WhyHotel','Travel','Washington D.C.'),
    ('Wish','Retail','SF Bay Area'),
    ('Wistia','Marketing','Boston');
INSERT INTO COMPANY VALUES
    ('Wix','Marketing','Tel Aviv'),
    ('Wizeline','Product','SF Bay Area'),
    ('Wonderschool','Education','SF Bay Area'),
    ('Wonolo','Recruiting','SF Bay Area'),
    ('Wordstream','Marketing','Boston'),
    ('Workable','Recruiting','Boston'),
    ('Workfront','Marketing','Salt Lake City'),
    ('WorkRamp','HR','SF Bay Area'),
    ('Workrise','Energy','Austin'),
    ('Worksmith','Retail','Austin'),
    ('Workstream','HR','SF Bay Area'),
    ('Woven','HR','Indianapolis'),
    ('Xendit','Finance','Jakarta'),
    ('Xerpa','HR','Sao Paulo'),
    ('Xiaohongshu','Consumer','Shanghai'),
    ('Yabonza','Real Estate','Sydney'),
    ('Yelp','Consumer','SF Bay Area'),
    ('Yoco','Finance','Cape Town'),
    ('Yojak','Construction','Gurugram'),
    ('Yonder','Media','Austin'),
    ('Zak','Food','Sao Paulo'),
    ('Zapp','Food','London'),
    ('Zappos','Retail','Las Vegas'),
    ('Zego','Finance','London'),
    ('Zeitgold','Finance','Berlin'),
    ('Zendesk','Support','SF Bay Area'),
    ('Zenefits','HR','SF Bay Area'),
    ('Zenius','Education','Jakarta'),
    ('Zenjob','HR','Berlin'),
    ('Zenoti','Fitness','Seattle'),
    ('Zepto','Finance','Brisbane'),
    ('Zerto','Infrastructure','Boston'),
    ('Zest AI','Finance','Los Angeles'),
    ('Zeus Living','Real Estate','SF Bay Area'),
    ('Zilingo','Retail','Singapore'),
    ('Zillow','Real Estate','Seattle'),
    ('Zinier','HR','SF Bay Area'),
    ('Zipcar','Transportation','Boston'),
    ('ZipRecruiter','Recruiting','Los Angeles'),
    ('Ziroom','Real Estate','Beijing'),
    ('Zola','Retail','New York City'),
    ('Zomato','Food','Jakarta'),
    ('Zomato','Food','Gurugram'),
    ('Zoomo','Transportation','Sydney'),
    ('Zoox','Transportation','SF Bay Area'),
    ('Zulily','Retail','Seattle'),
    ('Zum','Transportation','SF Bay Area'),
    ('Zume','Food','SF Bay Area'),
    ('Zumper','Real Estate','SF Bay Area'),
    ('Zwift','Fitness','Los Angeles');



INSERT INTO LOCATION(Name, CountryId)
VALUES
    ('SF Bay Area', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Jakarta', SELECT CountryId FROM COUNTRY WHERE Name = 'Indonesia'),
    ('Boston', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Lehi', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Eindhoven', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Austin', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Seattle', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Los Angeles',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Columbus', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Chicago',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Bengaluru', SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('Stockholm', SELECT CountryId FROM COUNTRY WHERE Name = 'Sweden'),
    ('Athens', SELECT CountryId FROM COUNTRY WHERE Name = 'Greece'),
    ('Sao Paulo',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Minneapolis', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('New York City',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Krakow', SELECT CountryId FROM COUNTRY WHERE Name = 'Poland'),
    ('Hyderabad',SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('Berlin',SELECT CountryId FROM COUNTRY WHERE Name = 'Germany'),
    ('Nebraska City', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Copenhagen',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Vancouver',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Tel Aviv',SELECT CountryId FROM COUNTRY WHERE Name = 'Israel'),
    ('Stamford',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Non/U.S.',SELECT CountryId FROM COUNTRY WHERE Name = 'Seychelles'),
    ('Trondheim',SELECT CountryId FROM COUNTRY WHERE Name = 'Norway'),
    ('Grand Rapids',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Oslo',SELECT CountryId FROM COUNTRY WHERE Name = 'Sweden'),
    ('Toronto',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Pittsburgh',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('DÃ¼sseldorf',SELECT CountryId FROM COUNTRY WHERE Name = 'Germany'),
    ('Montreal', SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Mumbai',SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('San Luis Obispo',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Jerusalem',SELECT CountryId FROM COUNTRY WHERE Name = 'Israel'),
    ('New Delhi',SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('Belo Horizonte',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Baltimore',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('London',SELECT CountryId FROM COUNTRY WHERE Name = 'United Kingdom'),
    ('Philadelphia',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('St. Louis',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Brussels',SELECT CountryId FROM COUNTRY WHERE Name = 'Belgium'),
    ('Buenos Aires',SELECT CountryId FROM COUNTRY WHERE Name = 'Argentina'),
    ('Noida',SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('The Hague',SELECT CountryId FROM COUNTRY WHERE Name = 'Netherlands'),
    ('Hong Kong',SELECT CountryId FROM COUNTRY WHERE Name = 'Hong Kong'),
    ('Singapore',SELECT CountryId FROM COUNTRY WHERE Name = 'Singapore'),
    ('Birmingham', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Auckland', SELECT CountryId FROM COUNTRY WHERE Name = 'New Zealand'),
    ('Salt Lake City',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Sydney',SELECT CountryId FROM COUNTRY WHERE Name = 'Australia'),
    ('Kuala Lumpur',SELECT CountryId FROM COUNTRY WHERE Name = 'Malaysia'),
    ('Munich',SELECT CountryId FROM COUNTRY WHERE Name = 'Germany'),
    ('Mexico City', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Las Vegas', SELECT CountryId FROM COUNTRY WHERE Name = 'United Kingdom'),
    ('Budapest',SELECT CountryId FROM COUNTRY WHERE Name = 'Hungary'),
    ('Atlanta', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Ho Chi Minh City', SELECT CountryId FROM COUNTRY WHERE Name = 'Vietnam'),
    ('Winnipeg',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Cairo',SELECT CountryId FROM COUNTRY WHERE Name = 'Egypt'),
    ('Denver',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Vienna',SELECT CountryId FROM COUNTRY WHERE Name = 'Austria'),
    ('Bangkok',SELECT CountryId FROM COUNTRY WHERE Name = 'Thailand'),
    ('Vilnius',SELECT CountryId FROM COUNTRY WHERE Name = 'Lithuania'),
    ('Raleigh',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Portland','United States'),
    ('Lagos',SELECT CountryId FROM COUNTRY WHERE Name = 'Nigeria'),
    ('Ottawa',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Richmond',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Bristol',SELECT CountryId FROM COUNTRY WHERE Name = 'United Kingdom'),
    ('Washington D.C.', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Melbourne',SELECT CountryId FROM COUNTRY WHERE Name = 'Australia'),
    ('Saskatoon',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Brisbane',SELECT CountryId FROM COUNTRY WHERE Name = 'Australia'),
    ('Porto Alegre',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Indianapolis',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Nairobi',SELECT CountryId FROM COUNTRY WHERE Name = 'Kenya'),
    ('Santiago',SELECT CountryId FROM COUNTRY WHERE Name = 'Chile'),
    ('Curitiba',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Dallas', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Miami', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Gurugram', SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('Luxembourg', SELECT CountryId FROM COUNTRY WHERE Name = 'Luxembourg'),
    ('Boulder', SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('New Haven',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Victoria',SELECT CountryId FROM COUNTRY WHERE Name = 'Seychelles'),
    ('Beijing', SELECT CountryId FROM COUNTRY WHERE Name = 'China'),
    ('Waterloo', SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Detroit',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Amsterdam',SELECT CountryId FROM COUNTRY WHERE Name = 'Netherlands'),
    ('Ferdericton',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Dakar',SELECT CountryId FROM COUNTRY WHERE Name = 'Senegal'),
    ('FlorianÃ³polis',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Lahore',SELECT CountryId FROM COUNTRY WHERE Name = 'Pakistan'),
    ('Santa Barbara',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Shenzen', SELECT CountryId FROM COUNTRY WHERE Name = 'China'),
    ('Durham',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Louisville',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Hamburg',SELECT CountryId FROM COUNTRY WHERE Name = 'Germany'),
    ('Nashua',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Huntsville',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Dubai',SELECT CountryId FROM COUNTRY WHERE Name = 'United Arab Emirates'),
    ('San Diego',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Spokane',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Bogota',SELECT CountryId FROM COUNTRY WHERE Name = 'Colombia'),
    ('Chennai',SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('Shanghai',SELECT CountryId FROM COUNTRY WHERE Name = 'China'),
    ('Reno',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Helsinki',SELECT CountryId FROM COUNTRY WHERE Name = 'Finland'),
    ('Lima',SELECT CountryId FROM COUNTRY WHERE Name = 'Peru'),
    ('Houston',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Malmo',SELECT CountryId FROM COUNTRY WHERE Name = 'Sweden'),
    ('Bend',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Dublin',SELECT CountryId FROM COUNTRY WHERE Name = 'Ireland'),
    ('Selangor',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Manama',SELECT CountryId FROM COUNTRY WHERE Name = 'Bahrain'),
    ('Karachi',SELECT CountryId FROM COUNTRY WHERE Name = 'Pakistan'),
    ('Bucharest',SELECT CountryId FROM COUNTRY WHERE Name = 'Romania'),
    ('Istanbul',SELECT CountryId FROM COUNTRY WHERE Name = 'Turkey'),
    ('Cincinnati',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Moscow',SELECT CountryId FROM COUNTRY WHERE Name = 'Russia'),
    ('Phoenix',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Davenport',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Calgary',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Nashville',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Montevideo',SELECT CountryId FROM COUNTRY WHERE Name = 'Uruguay'),
    ('Edinburgh',SELECT CountryId FROM COUNTRY WHERE Name = 'United Kingdom'),
    ('Fayetteville',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Madison',SELECT CountryId FROM COUNTRY WHERE Name ='United States'),
    ('Sofia',SELECT CountryId FROM COUNTRY WHERE Name ='Bulgaria'),
    ('Santa Fe',SELECT CountryId FROM COUNTRY WHERE Name ='United States'),
    ('Cork',SELECT CountryId FROM COUNTRY WHERE Name ='Ireland'),
    ('Paris',SELECT CountryId FROM COUNTRY WHERE Name = 'France'),
    ('Ahmedabad',SELECT CountryId FROM COUNTRY WHERE Name = 'India'),
    ('Joinville',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Hanoi',SELECT CountryId FROM COUNTRY WHERE Name = 'Vietnam'),
    ('Norwalk',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Zurich',SELECT CountryId FROM COUNTRY WHERE Name = 'Switzerland'),
    ('Tallin', SELECT CountryId FROM COUNTRY WHERE Name = 'Estonia'),
    ('Dusseldorf',SELECT CountryId FROM COUNTRY WHERE Name = 'Germany'),
    ('Lisbon',SELECT CountryId FROM COUNTRY WHERE Name = 'Portugal'),
    ('Cape Town',SELECT CountryId FROM COUNTRY WHERE Name = 'South Africa'),
    ('Missoula',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Guadalajara',SELECT CountryId FROM COUNTRY WHERE Name = 'Mexico'),
    ('Blumenau',SELECT CountryId FROM COUNTRY WHERE Name = 'Brazil'),
    ('Milwaukee',SELECT CountryId FROM COUNTRY WHERE Name ='United States'),
    ('Ann Arbor',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Quebec',SELECT CountryId FROM COUNTRY WHERE Name = 'Canada'),
    ('Prague',SELECT CountryId FROM COUNTRY WHERE Name = 'Czech Republic'),
    ('Yangon',SELECT CountryId FROM COUNTRY WHERE Name = 'Myanmar'),
    ('New Orleans',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Sacramento',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Charlotte',SELECT CountryId FROM COUNTRY WHERE Name = 'United States'),
    ('Tampa Bay',SELECT CountryId FROM COUNTRY WHERE Name = 'United States');
    
INSERT INTO INDUSTRY(Name) 
VALUES
   ('Aerospace'),
   ('Construction'),
   ('Consumer'),
   ('Crypto'),
   ('Data'),
   ('Education'),
   ('Energy'),
   ('Finance'),
   ('Fitness'),
   ('Food'),
   ('Healthcare'),
   ('HR'),
   ('Industry'),
   ('Infrastuture'),
   ('Legal'),
   ('Logistics'),
   ('Marketing'),
   ('Media'),
   ('Other'),
   ('Product'),
   ('Real Estate'),
   ('Recruiting'),
   ('Retail'),
   ('Sales'),
   ('Security'),
   ('Support'),
   ('Transportation'),
   ('Travel');
